%YAML 1.2
---
# This is an example config file for OS-Installer.
# Place your config under /etc/os-installer/config.yaml for it to be used.
# If a value is not defined, its default will be used.

# Some strings can have translations. Use the config_to_pot.py script to
# extract them into a .pot file, from which translations can be created.
# Place the translation .po files in /etc/os-installer/po/.

# Name of the distribution.
# Default: 'Untitled'
distribution_name: 'Debuntorarch'

# Whether the installation needs an internet connection.
# Default: yes
internet_connection_required: yes

# A URL/IP address to be used to check for an existing internet connection.
# Default: 'http://nmcheck.gnome.org/check_network_status.txt'
internet_checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

# Skip the language selection dialog by specifing a language, e.g. 'pt_BR'
# Default: no (No fixed language, not Norwegian)
fixed_language: no

# A selection of languages the installer should present by default.
# Note: For a language to be available, it needs to be provided by the system
# and the installer needs to have a translation into that language.
# Default: ['ar', 'de', 'en', 'es', 'fr', 'ja', 'ru', 'zh']
suggested_languages:
    - 'ar'
    - 'de'
    - 'en'
    - 'es'
    - 'fr'
    - 'ja'
    - 'ru'
    - 'zh'

# Show a welcome page after language selection.
#
# logo    string  Optional. Path to a logo (e.g. distribution logo)
# text_LC string  Optional. Welcome text. Translatable.
# usage   bool    Whether to show a welcome page at all.
#
# Default: logo: None, text: None, usage: yes
welcome_page:
    logo    : '/your/distribution/logo.png'
    text    : 'A welcoming text to inform about the installation.'
    usage   : yes

# Minimum disk size needed for the installation (in Gigabyte)
# Default: 5
minimum_disk_size: 5

# Whether to offer setting a disk encryption PIN
# Default: yes
offer_disk_encryption: yes

# gnome-initial-setup can handle user and locale setup.
# These settings allow to disable these pages.
#
# Default: skip_user: no, skip_locale: no
skip_user: no
skip_locale: no

# List of software that can additionally be selected for installation.
# Each package requires a 'name' and one of either
#   * 'keyword' with optional 'suggested'
#   * 'options'
#
#
# name            string  Name presented to user. Translatable.
# description     string  Optional. Description presented to user. Translatable.
# icon_path       string  Optional. Absolute path to icon to be displayed.
# keyword         string  Forwarded to the installation script as is.
# suggested       bool    Optional. Whether installation defaults to yes.
# options         list    A list of options, with each option having:
#     name        string  Optional. Name presented to user. Translatable.
#                         Value of 'option' is used when not given.
#     option      string  Like 'keyword' for non-options, forwarded as-is when chosen.
#
# Default: [], suggested: False, description: '', icon_path: fallback icon
additional_software:
    - name           : 'Firefox'
      description    : 'Popular Web Browser from Mozilla'
      icon_path      : '/etc/os-installer/icons/firefox.png'
      keyword        : 'firefox'
      suggested      : yes
    - name           : 'Files'
      description    : 'Access and organize files'
      icon_path      : '/etc/os-installer/icons/nautilus.svg'
      keyword        : 'nautilus'
      suggested      : yes
    - name           : 'Optional Option'
      description    : 'Select your favorite option'
      icon_path      : '/etc/os-installer/icons/options-symbolic.svg'
      options        :
        - option     : 'Nothing'
        - name       : 'Option 1'
          option     : 'package_1'
        - name       : 'Option 2'
          option     : 'package_2'

# List of features that can additionally be selected. Very similar
# to `additional_software`, but meant for more generic features. Can
# be used instead of or in combination with `additional_software`.
#
# See `additional_software` for syntax description.
additional_features:
    - name           : 'Dummy Feature'
      description    : 'Does not do anything'
      keyword        : 'dummy'
    - name           : 'Snapshots'
      description    : 'Snapshots allow restoring a previous state of your system'
      icon_path      : '/etc/os-installer/icons/snapshot.svg'
      keyword        : 'snapshots'
      suggested      : yes

# Upon failure an option to search for help on the internet is given.
# The url this leads to can be defined here. The squiggly brackets are
# replaced with the os-installer version.
#
# Default: 'https://duckduckgo.com/?q="os-installer {}"+"failed installation"'
failure_help_url: 'https://support.dist.ro/new_issue?q="failed"+"os-installer {}"'

# Certain parts of the installer launch external programs. These can be configured here.
# Note: For calling the command, the string is split up by spaces.
#
# The browser_cmd will be called followed by a url.
#
# Default: browser_cmd: 'epiphany', disks_cmd: 'gnome-disks', wifi_cmd: 'gnome-control-center wifi'
browser_cmd: 'firefox'
disks_cmd  : 'gnome-disks'
wifi_cmd   : 'gnome-control-center wifi'