%YAML 1.2
---
# This is an example config file for OS-Installer.
# Place your config under /etc/os-installer/config.yaml for it to be used.
# If a value is not defined, its default will be used.

# Some strings can have translations. Use the config_to_pot.py script to
# extract them into a .pot file, from which translations can be created.
# Place the translation .po files in /etc/os-installer/po/.

# Name of the distribution.
# Default: 'Untitled'
distribution_name: 'Debuntorarch'

# After gathering all configured information, os-installer runs the scripts
# configured here. The installation can happen in up to three phases. A phase
# will be skipped if no script is configured for it.
#
# To see what is available per phase, see the examples scripts. If an "install"
# phase is configured, the installer behave slightly different:
# * A separate confirmation page is shown before user configuration happens
# * Navigating to pre-confirmation pages is not possible after confirmation
# * Language, desktop and disk choices can not be changed from the summary page
#
# If an internet connection is required, it will be available for all phases.
#
# prepare   - Run directly or when an internet connection is available.
# install   - Run with locale, disk and optional desktop configured.
# configure - Run with everything configured.
#
# Default: None
scripts:
  prepare: /etc/os-installer/scripts/prepare.sh
  install: /etc/os-installer/scripts/install.sh
  configure: /etc/os-installer/scripts/configure.sh

# Configure whether an internet connection is required. Optionally set what
# URL/IP address is used to check for an existing internet connection.
#
# Default: connection_required: yes, checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'
internet:
  connection_required: yes
  checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

# Skip the language selection dialog by specifing a language, e.g. 'pt_BR'
# Default: no (No fixed language, not Norwegian)
fixed_language: no

# Some languages can be presented more prominently. All other languages are
# shown in an alphabetical order.
# Note: For a language to be available, it needs to be provided by the system
# and the installer needs to have a translation into that language.
# Default: []
suggested_languages:
  - 'ar'
  - 'de'
  - 'en'
  - 'es'
  - 'fr'
  - 'ja'
  - 'ru'
  - 'zh'

# Show a welcome page after language selection.
#
# logo    string  Optional. Path to a logo (e.g. distribution logo)
# text_LC string  Optional. Welcome text. Translatable.
# usage   bool    Whether to show a welcome page at all.
#
# Default: logo: None, text: None, usage: yes
welcome_page:
  logo    : '/etc/os-installer/distro.svg'
  text    : 'A welcoming text to inform about the installation.'
  usage   : yes

# Disk requirements for installation
#
# partition_ok  Whether partitions are accepted as installation targets
#                (Otherwise only complete disks can be used)
# min_size       Minimum size needed for installation (in Gigabyte)
#
# Default: partition_ok: no, min_size: 5
disk:
  partition_ok: yes
  min_size: 5

# Disk encryption PIN setup.
#
# offered      Whether to offer disk encryption pin setup.
# forced       Whether to requrie a disk encryption pin.
# min_length   Minimal encryption pin length.
# confirmation Require pin to be entered a second time.
#
# Default: offered: yes, forced: no, min_length: 1, confirmation: no
disk_encryption:
  offered: yes
  forced: no
  min_length: 1
  confirmation: yes

# Provide multiple desktop environments to choose from
#
# name        string  Name of desktop. Translatable.
# description string  Optional. Short descripiton of the desktop.
# image_path  string  Absolute path of an image to display.
# keyword     string  Forwarded to the installation script as is.
#
# Default: [] (no desktop selection page)
desktop:
  - name        : 'GNOME'
    description : 'Simple desktop that can be personalized with extensions.'
    image_path  : '/etc/os-installer/desktops/gnome.jpg'
    keyword     : 'gnome'
  - name        : 'KDE Plasma'
    description : 'Configurable desktop that is similar to Windows.'
    image_path  : '/etc/os-installer/desktops/kde.png'
    keyword     : 'kde'
  - name        : 'Xfce'
    description : 'Lightweight desktop with focus on modularity.'
    image_path  : '/etc/os-installer/desktops/xfce.png'
    keyword     : 'xfce'
  - name        : 'Enlightenment'
    description : 'Highly configurable, lightweight desktop for tinkerers.'
    image_path  : '/etc/os-installer/desktops/enlightenment.png'
    keyword     : 'enlightenment'

# User setup requests a printable name and a password by default.
#
# request_username      Request a username. Otherwise generated from name.
# provide_autologin     Whether to present an autologin option.
# min_password_length   Minimal password length.
# password_confirmation Require password to be entered a second time.
#
# Default: request_username: no, provide_autologin: no, min_password_length: 1, password_confirmation: no
user:
  request_username: yes
  provide_autologin: yes
  min_password_length: 1
  password_confirmation: yes

# gnome-initial-setup can handle user and locale setup.
# These settings allow to disable these pages.
#
# Default: skip_user: no, skip_locale: no
skip_user: no
skip_locale: no

# List of software that can additionally be selected for installation.
# Each package requires a 'name' and one of either
#   * 'keyword' with optional 'suggested'
#   * 'options'
#
#
# name            string  Name presented to user. Translatable.
# description     string  Optional. Description presented to user. Translatable.
# icon_path       string  Optional. Absolute path to icon to be displayed.
# keyword         string  Forwarded to the installation script as is.
# suggested       bool    Optional. Whether installation defaults to yes.
# options         list    A list of options, with each option having:
#     name        string  Optional. Name presented to user. Translatable.
#                         Value of 'option' is used when not given.
#     option      string  Optional. Like 'keyword' for non-options, forwarded as-is when chosen.
#                         Empty string is used when not given.
#
# Default: [], suggested: no, description: '', icon_path: fallback icon
additional_software:
  - name           : 'Firefox'
    description    : 'Popular Web Browser from Mozilla'
    icon_path      : '/etc/os-installer/icons/firefox.png'
    keyword        : 'firefox'
    suggested      : yes
  - name           : 'Chr👁️me'
    description    : 'Spyware made by big brother'
    keyword        : 'börk'
    suggested      : no
  - name           : 'Files'
    description    : 'Access and organize files'
    icon_path      : '/etc/os-installer/icons/nautilus.svg'
    keyword        : 'nautilus'
    suggested      : yes
  - name           : 'Optional Option'
    description    : 'Select your favorite option'
    icon_path      : '/etc/os-installer/icons/options-symbolic.svg'
    options        :
      - name       : 'Nothing'
      - name       : 'Option 1'
        option     : 'package_1'
      - name       : 'Option 2'
        option     : 'package_2'

# List of features that can additionally be selected. Very similar
# to `additional_software`, but meant for more generic features. Can
# be used instead of or in combination with `additional_software`.
#
# See `additional_software` for syntax description.
additional_features:
  - name           : 'Dummy Feature'
    description    : 'Does not do anything'
    keyword        : 'dummy'
  - name           : 'Snapshots'
    description    : 'Snapshots allow restoring a previous state of your system'
    icon_path      : '/etc/os-installer/icons/snapshot.svg'
    keyword        : 'snapshots'
    suggested      : yes
  - name           : 'Background Image'
    options        :
      - name       : 'Axolotls'
        option     : 'bg-axolotl'
      - name       : 'Cats'
        option     : 'bg-cats'
      - name       : 'Dogs'
        option     : 'bg-dogs'

# A slideshow can be shown during the installation process.
# Images are displayed in order and cycled through.
# Each image is shown for the defined amount of seconds or 5 otherwise.
# If not configured, a basic spinner is shown.
#
# Default: []
install_slideshow:
  - image_path: '/etc/os-installer/desktops/enlightenment.png'
    seconds: 1
  - image_path: '/etc/os-installer/desktops/gnome.jpg'
    seconds: 3
  - image_path: '/etc/os-installer/desktops/kde.png'
  - image_path: '/etc/os-installer/desktops/xfce.png'
    seconds: 7

# Upon failure an option to search for help on the internet is given.
# The url this leads to can be defined here. The squiggly brackets are
# replaced with the os-installer version.
#
# Default: 'https://duckduckgo.com/?q="os-installer {}"+"failed installation"'
failure_help_url: 'https://support.dist.ro/new_issue?q="failed"+"os-installer {}"'

# Certain parts of the installer launch external programs. These can be configured here.
# Note: For calling the command, the string is split up by spaces.
#
# The browser_cmd will be called followed by a url.
#
# Default: browser: 'epiphany', disks: 'gnome-disks', reboot: 'reboot', wifi: 'gnome-control-center wifi'
commands:
  browser: 'firefox'
  disks  : 'gnome-disks'
  reboot : 'shutdown -r now'
  wifi   : 'gnome-control-center wifi'
